### PR TITLE
unittest.TestCase().assertItemsEqual() --> assertCountEqual()

### PR DESCRIPTION
**Pull request by cclauss**
* https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertItemsEqual -->
* https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertCountEqual
```
======================================================================
ERROR: test_random_policy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/test_as_server.py", line 62, in check
    result = fun(*argv, **kwargs)
  File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/Core/CreditMining/test_credit_mining_policies.py", line 35, in test_random_policy
    self.assertItemsEqual(self.torrents, sorted_torrents, 'Arrays contains different torrents')
AttributeError: 'TestCreditMiningPolicies' object has no attribute 'assertItemsEqual'

======================================================================
ERROR: test_seederratio_policy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/test_as_server.py", line 62, in check
    result = fun(*argv, **kwargs)
  File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/Core/CreditMining/test_credit_mining_policies.py", line 47, in test_seederratio_policy
    self.assertItemsEqual(sorted_torrents, expected_torrents, 'Arrays contains different torrents')
AttributeError: 'TestCreditMiningPolicies' object has no attribute 'assertItemsEqual'

======================================================================
ERROR: Tests both UploadPolicy and InvestmentPolicy since they both sorts torrents based on upload.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/test_as_server.py", line 62, in check
    result = fun(*argv, **kwargs)
  File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/Core/CreditMining/test_credit_mining_policies.py", line 76, in test_upload_based_policy_sort
    self.assertItemsEqual(sorted_torrents1, expected_torrents1, 'Arrays contains different torrents')
AttributeError: 'TestCreditMiningPolicies' object has no attribute 'assertItemsEqual'
```

### CODE REVIEW

**Comment by cclauss** [comment]
Retest this please

**Comment by cclauss** [comment]
Retest this please

**Comment by qstokkink** [comment]
In IPv8 I replaced `assertItemsEqual` with `assertSetEqual`, which is, I think, a better replacement.

**Comment by xoriole** [comment]
retest this please

**Comment by devos50** [comment]
`assertSetEqual` cannot be used by a `list` apparently:

```
first argument does not support set difference: 'list' object has no attribute 'difference'
```

**Comment by devos50** [comment]
I'm going to ignore the failing win64 tests for now - we are working on a fix in #4417
