### ISSUE TITLE
tribler 6.4.3 cannot start

### ISSUE THREAD

**Issue by xantares** [Tribler/tribler#1754]
Hi,
I can't get v6.4.3 to work on archlinux (6.5rc6 was running, but it's not stable): https://aur.archlinux.org/packages/tribler/
here's a traceback:
```
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Main/tribler_main.py", line 1112, in run
    abc = ABCApp(params, installdir, is_unit_testing)
  File "/usr/share/tribler/Tribler/Main/tribler_main.py", line 175, in __init__
    session = self.InitStage1(installdir)
  File "/usr/share/tribler/Tribler/Main/tribler_main.py", line 371, in InitStage1
    dlcfgfilename = get_default_dscfg_filename(self.sconfig.get_state_dir())
  File "/usr/share/tribler/Tribler/Main/globals.py", line 50, in get_default_dscfg_filename
    return os.path.join(state_dir, STATEDIR_DLCONFIG)
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
SessionConfigInterface.get_state_dir returns None, any help on this ?

**Comment by whirm** [comment]
Did you run 6.5 and then go back to 5.4.3 without deleting ~/.Tribler?

**Comment by xantares** [comment]
indeed!

**Comment by whirm** [comment]
Glad to help! 
We should add a check so you get an error instead of weird behaviour. I'll create an issue for that.
