### PR TITLE
Fix for torrent renaming

### LINKED ISSUE #6623: I cannot rename created torrents anymore
**Describe the bug**
I created a torrent, added it to my channel, then tried to rename it. An error occurred.

```
An error occurred during the request:

Traceback (most recent call last):
  File "tribler_core\components\restapi\rest\rest_manager.py", line 59, in error_middleware
  File "aiohttp\web_middlewares.py", line 117, in impl
  File "tribler_core\components\metadata_store\restapi\metadata_endpoint.py", line 155, in update_channel_entry
  File "<string>", line 2, in update_entry
  File "pony\orm\core.py", line 533, in new_func
  File "tribler_core\components\metadata_store\restapi\metadata_endpoint.py", line 43, in update_entry
  File "tribler_core\components\metadata_store\db\orm_bindings\channel_node.py", line 265, in update_properties
AttributeError: 'TorrentMetadata' object has no attribute ''
```

**To Reproduce**
1. Create a channel.
2. Create a torrent there.
3. Try to rename it.

**Expected behavior**
The torrent is renamed. It worked fine on 7.10.0.

**Screenshots**

tribler_2021-12-05_18-56-16

You can see both the old (AMD64) and new (MidnightBSD 2.1.2 AMD64) name. The latter is not applied.

**Desktop (please complete the following information):**
 - OS: Windows 11.
 - Tribler's version: 7.11 RC1.

### PR DESCRIPTION
**Pull request by ichorid**
fixes #6623  (courtesy of @devos50 )

I'll provide the test for the thing later on `main` - created[ an issue](#6631 ) for that.

### CODE REVIEW

**Comment by ichorid** [comment]
retest this please

**Review by kozlovsky — APPROVED** [review]
