### ISSUE TITLE
e2e payout test fails randomly

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5162]
This happens mostly on Windows. The problem is, `TriblerTunnelCommunity` really *depends* on `session` and `session.ltmgr`, however its `__init__` method and associated test are a horrible mess :hankey: :boom: :skull:

So, sometimes the test just fails to find `ltmgr`. Because no one provided it with one.

```python
======================================================================
FAIL: Check if payouts work for an e2e-linked circuit
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\site-packages\asynctest\case.py", line 297, in run
    self._run_test_method(testMethod)
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\site-packages\asynctest\case.py", line 354, in _run_test_method
    self.loop.run_until_complete(result)
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\site-packages\asynctest\case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_async_win64\tribler\src\tribler-core\tribler_core\modules\tunnel\tests\test_triblertunnel_community.py", line 336, in test_payouts_e2e
    self.assertTrue(self.nodes[2].overlay.bandwidth_wallet.get_bandwidth_tokens() > 0)
AssertionError: False is not true


ERROR   1582892237       community:TriblerTunnelCommunity:678  Exception occurred while handling packet!
Traceback (most recent call last):
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_async_win64\tribler\src\pyipv8\ipv8\messaging\anonymization\community.py", line 673, in on_packet_from_circuit
    result = handler(source_address, data, circuit_id)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_async_win64\tribler\src\tribler-core\tribler_core\modules\tunnel\community\triblertunnel_community.py", line 513, in on_rendezvous_established
    self.update_ip_filter(circuit.info_hash)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_async_win64\tribler\src\tribler-core\tribler_core\modules\tunnel\community\triblertunnel_community.py", line 517, in update_ip_filter
    lt_session = self.tribler_session.ltmgr.get_session(download.config.get_hops())
AttributeError: 'NoneType' object has no attribute 'ltmgr'
```

**Comment by devos50** [comment]
Since `self.tribler_session` is an optional argument in the tunnel community class, we should check if this value is not `None` when the `update_ip_filter` is called. This most likely won't fix the root cause of this error (since for some reason, `self.tribler_session` is still `None`) but at least it won't crash.

**Comment by ichorid** [comment]
I don't like this solution. This is the easiest way to mask some really bad problems. Instead, I propose to refactor the `__init__` method so it will require `ltmgr` argument explicitly.

**Comment by devos50** [comment]
I didn't say it's a solution; it's a change to make the code more consistent with the rest of the file (where we check if `self.tribler_session` is `None` before we do something with it).

**Comment by devos50** [comment]
I haven't seen this test failing for a long time; closing this issue.
