### ISSUE TITLE
I cannot rename created torrents anymore

### ISSUE THREAD

**Issue by dertuxmalwieder** [Tribler/tribler#6623]
**Describe the bug**
I created a torrent, added it to my channel, then tried to rename it. An error occurred.

```
An error occurred during the request:

Traceback (most recent call last):
  File "tribler_core\components\restapi\rest\rest_manager.py", line 59, in error_middleware
  File "aiohttp\web_middlewares.py", line 117, in impl
  File "tribler_core\components\metadata_store\restapi\metadata_endpoint.py", line 155, in update_channel_entry
  File "<string>", line 2, in update_entry
  File "pony\orm\core.py", line 533, in new_func
  File "tribler_core\components\metadata_store\restapi\metadata_endpoint.py", line 43, in update_entry
  File "tribler_core\components\metadata_store\db\orm_bindings\channel_node.py", line 265, in update_properties
AttributeError: 'TorrentMetadata' object has no attribute ''
```

**To Reproduce**
1. Create a channel.
2. Create a torrent there.
3. Try to rename it.

**Expected behavior**
The torrent is renamed. It worked fine on 7.10.0.

**Screenshots**

![tribler_2021-12-05_18-56-16](https://user-images.githubusercontent.com/125629/144757740-d6e8d222-0c3c-49e4-9593-c35910aa4402.png)

You can see both the old (AMD64) and new (MidnightBSD 2.1.2 AMD64) name. The latter is not applied.

**Desktop (please complete the following information):**
 - OS: Windows 11.
 - Tribler's version: 7.11 RC1.
